#!/bin/bash
#
# cpreq
# 
# Purpose: copy one or more files which are required for an
# application to run. The files must have size > 0.
#
# cpreq behaves similar to cp and accepts all valid cp options.
# It accepts an additional option -z that allows files with size
# zero to be copied.
#
# Error codes:
#   1 : command failed on `cp`
#   2 : one or more files have size zero and '-z' was not specified
#

if [[ $# -lt 2 ]]; then
  echo "Usage: $( basename "$0" ) [-z] [OPTION] SOURCE [...] DEST"
  exit 1
fi

cp_args=()
cp_opts=()
zero_byte="FALSE"
while [[ $# -gt 0 ]]; do
  case $1 in
    -z)
      zero_byte="TRUE"
      shift
      ;;
    # 'cp -t' reverses source/directory arguments
    # so it needs special handling
    -t)
      cp_args+=("$1")
      shift
      ;;
    -*)
      cp_opts+=("$1")
      shift
      ;;
    *)
      cp_args+=("$1")
      shift
      ;;
  esac
done

# Handle 'cp -t' case
if [[ "${cp_args[*]}" =~ [[:space:]]?-t[[:space:]] ]]; then
  targets=("${cp_args[@]#*-t}")
  targets=("${targets[@]:1}")
else
  n_targets=$(( ${#cp_args[@]} - 1 ))
  targets=("${cp_args[@]:0:$n_targets}")
fi

zero_byte_files=$( find "${targets[@]}" -size 0 -print )
if [[ "$zero_byte" != "TRUE" ]] && [[ -n "$zero_byte_files" ]]; then
    export err=2; err_chk "One or more input files have size zero: ${zero_byte_files[*]}"
fi

cmd="cp ${cp_opts[*]} ${cp_args[*]}"
$cmd
export err=$?; err_chk "'$cmd' was not successful."
